from rest_framework import serializers

class EventSerializer(serializers.Serializer):
    id = serializers.CharField(required=False)
    name = serializers.CharField()
    description = serializers.CharField(required=False, allow_blank=True, allow_null=True)
    type = serializers.CharField(required=False, allow_blank=True, allow_null=True)
    startDate = serializers.CharField()
    endDate   = serializers.CharField()
    venue = serializers.CharField(required=False, allow_blank=True, allow_null=True)
    address = serializers.CharField(required=False, allow_blank=True, allow_null=True)
    capacity = serializers.IntegerField(required=False)
    expectedAttendees = serializers.IntegerField(required=False)
    actualAttendees   = serializers.IntegerField(required=False)
    budget = serializers.IntegerField(required=False)
    dietaryNeeds = serializers.IntegerField(required=False)
    accessibilityNeeds = serializers.IntegerField(required=False)
    status = serializers.CharField(required=False, allow_blank=True, allow_null=True)
    priority = serializers.CharField(required=False, allow_blank=True, allow_null=True)
    notes = serializers.CharField(required=False, allow_blank=True, allow_null=True)
    tags = serializers.ListField(child=serializers.CharField(), required=False)
    createdBy = serializers.CharField()
    createdAt = serializers.CharField(required=False)
    updatedAt = serializers.CharField(required=False)
